apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvolume1 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /volume1/uptemp/Santhana 
    #server: videos.dvs.lab.atl.arrisi.com
    server: 10.19.30.230 
  persistentVolumeReclaimPolicy: Retain 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim1
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi
